### ISSUE TITLE
Session Changer throwing AuthenticationUnavalibleException

### ISSUE THREAD

**Issue by fakename131** [egold555/MCP-Snippets#4]
When I use the session changer, I get a few errors:

AuthenticationUnavailableException:

> com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
> 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:71)
> 	at com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication.logInWithPassword(YggdrasilUserAuthentication.java:74)
> 	at com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication.logIn(YggdrasilUserAuthentication.java:57)
> 	at egold555.SessionChanger.setUser(SessionChanger.java:40)
> 	at axolotl.Main.startup(Main.java:17)
> 	at net.minecraft.client.Minecraft.startGame(Minecraft.java:602)
> 	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
> 	at net.minecraft.client.main.Main.main(Main.java:115)
> 	at Start.main(Start.java:10)

SSLException:

> Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
> 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
> 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1958)
> 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1915)
> 	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1898)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1419)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1396)
> 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
> 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
> 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
> 	at com.mojang.authlib.HttpAuthenticationService.performPostRequest(HttpAuthenticationService.java:73)
> 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:54)
> 	... 8 more

RuntimeException:

> Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
> 	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
> 	at sun.security.validator.Validator.getInstance(Validator.java:179)
> 	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
> 	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
> 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
> 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
> 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1508)
> 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:215)
> 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1024)
> 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:954)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1065)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1384)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1412)
> 	... 16 more

and InvalidAlgorithmParameterException:

> Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
> 	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
> 	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
> 	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
> 	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
> 	... 28 more

and idk why I got them.

**Comment by fakename131** [comment]
I fixed it by replacing the $JAVA_HOME/jre/lib/ssl/cacerts file
