### ISSUE TITLE
How to use Animated Resource Location

### ISSUE THREAD

**Issue by Pepe-77777** [egold555/MCP-Snippets#5]
i am getting errors on use animated;

```
java.lang.NullPointerException
	at JIRAYACLIENT.ui.JirayaClientMainMenu.ClientTick(JirayaClientMainMenu.java:34) ~[bin/:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1731) ~[bin/:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1108) ~[bin/:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:423) [bin/:?]
	at net.minecraft.client.main.Main.main(Main.java:113) [bin/:?]
	at Start.main(Start.java:11) [bin/:?]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 02/10/22 20:55
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at JIRAYACLIENT.ui.JirayaClientMainMenu.ClientTick(JirayaClientMainMenu.java:34)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1731)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1108)
	at net.minecraft.client.Minecraft.run(Minecraft.java:423)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at Start.main(Start.java:11)
```

**Comment by thasave14** [comment]
I can't help you without more errors
